### ISSUE TITLE
没有方法

### ISSUE THREAD

**Issue by xulong20130712** [tiann/epic#1]
这个只是在ART的虚拟机上才能用吧，那如果不是ART的请问还有什么方法能hook吗，

**Comment by tiann** [comment]
@xulong20130712 dalvik上的hook已经非常非常成熟了，比如 [dexposed](https://github.com/alibaba/dexposed), [adbi](https://github.com/crmulliner/adbi)

**Comment by xulong20130712** [comment]
我指的是有没有也是直接通过像你这种比较简单的直接就能动态替换方法的方式，你在dalvik上有试过吗。

**Comment by tiann** [comment]
@xulong20130712 没试过，也没必要，dalvik都快淘汰了，研究它干啥。
