### ISSUE TITLE
监控线程创建时在before回调里面无法拿到创建线程的具体堆栈

### ISSUE THREAD

**Issue by iyy** [tiann/epic#16]
有什么方法可以做到吗 主要用来监控野线程是由那个业务生成的

**Comment by tiann** [comment]
可以拿到的，直接 new RuntimeException() 不就可以了？

**Comment by iyy** [comment]
`public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(newBase);
        hook();
    }

    private void hook() {
        DexposedBridge.hookAllConstructors(Thread.class, new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                Log.d(TAG, Log.getStackTraceString(new RuntimeException()));
            }
        });

        DexposedBridge.hookAllMethods(Thread.class, "run", new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                Log.d(TAG, "run" + Log.getStackTraceString(new RuntimeException()));
                super.beforeHookedMethod(param);
            }
        });
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        new Thread() {
            @Override
            public void run() {
                Log.d(TAG, "run");
            }
        }.start();

    }`

堆栈只到
![image](https://user-images.githubusercontent.com/1791358/34340477-3a2245b2-e9bf-11e7-9d95-9c537ad9f62f.png)

**Comment by iyy** [comment]
`public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(newBase);
        hook();
    }

    private void hook() {
        DexposedBridge.hookAllConstructors(Thread.class, new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                Log.d(TAG, Log.getStackTraceString(new RuntimeException()));
                super.beforeHookedMethod(param);
            }
        });

        DexposedBridge.hookAllMethods(Thread.class, "run", new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                Log.d(TAG, "run" + Log.getStackTraceString(new RuntimeException()));
                super.beforeHookedMethod(param);
            }
        });
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        new Thread() {
            @Override
            public void run() {
                Log.d(TAG, "run");
            }
        }.start();

   }

}`
单步跟踪的时候是可以看到完整堆栈的
打印的时候就只有四行
![image](https://user-images.githubusercontent.com/1791358/34340614-63c0140a-e9c2-11e7-9917-f658700b4f50.png)

**Comment by iyy** [comment]
另外在 beforeHookedMethod抛出异常的话 打印堆栈也会消失,只有一行
荣耀6 android6.0
12-25 22:31:45.531 10553 10553 I DexposedBridge: java.lang.RuntimeException

**Comment by chago** [comment]
@iyy 看看这个行不 
public static String GetStack() {
        String result = "";
        Throwable ex = new Throwable();
        StackTraceElement[] stackElements = ex.getStackTrace();
        if (stackElements != null) {
            int range_start = 0;
            int range_end = Math.min(stackElements.length, 12);
            if (range_end < range_start) return "";

            for (int i = range_start; i < range_end; i++) {

                result = result + (stackElements[i].getClassName() + "->");
                result = result + (stackElements[i].getMethodName()) + "  ";
                result = result + (stackElements[i].getFileName() + "(");
                result = result + (stackElements[i].getLineNumber() + ")\n");
                result = result + ("-----------------------------------\n");
            }
        }
        return result;
    }

**Comment by tiann** [comment]
@iyy 关注一下线程的启动流程，你会发现：

线程启动通过start方法，通过JNI进入到虚拟机，然后又通过JNI回调Java层的run方法；因此run方法的顶层调用栈是native方法，你代码的结果是正常的：bridge就是最顶层的Java方法。

如果需要监控线程的创建，请Hook start方法：

```java
            DexposedBridge.findAndHookMethod(Thread.class, "start", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    super.beforeHookedMethod(param);
                    Thread t = (Thread) param.thisObject;
                    String threadName = t.getName();
                    android.util.Log.i(TAG, threadName + " is started by:", new RuntimeException("stack"));
                }
            });
```

**Comment by iyy** [comment]
@tiann 今天我也发现了 谢谢回复~~
