### ISSUE TITLE
libdexposed.so源码

### ISSUE THREAD

**Issue by jarno520** [tiann/epic#18]
你好，你的项目中的libdexposed.so，我找阿里开源的dexposed.so替换后无法运行，你是不是对dexposed.so的源码进行了修改？可以把这个源码也开源出来吗？

**Comment by jarno520** [comment]
4.4的机器上加载so就失败了
01-15 21:48:58.313 4140-4140/me.weishu.epic.samples I/DexposedBridge: java.lang.NoSuchMethodError: no static or non-static method "Lcom/taobao/android/dexposed/DexposedBridge;.initNative()Z"
                                                                          at java.lang.Runtime.nativeLoad(Native Method)

**Comment by tiann** [comment]
sorry，这是个BUG。

**Comment by jarno520** [comment]
能给可以编译的dexposed.so的源码且适合我们epic跑的吗？

**Comment by tiann** [comment]
没有，你可以改了发个PR。
