### ISSUE TITLE
epic在6.0上加载失败

### ISSUE THREAD

**Issue by jarno520** [tiann/epic#19]
No implementation found for long me.weishu.epic.art.EpicNative.getMethodAddress(java.lang.reflect.Member) (tried Java_me_weishu_epic_art_EpicNative_getMethodAddress and Java_me_weishu_epic_art_EpicNative_getMethodAddress__Ljava_lang_reflect_Member_2)

**Comment by tiann** [comment]
x86吗

**Comment by tiann** [comment]
编译问题吧，看看你编译出来的apk里面有没有libepic.so。

**Comment by jarno520** [comment]
抱歉，是我so库加载错了，64位的把32位的加载进来
