### ISSUE TITLE
如果要hook    android.app.Activity的onCreate方法呢？

### ISSUE THREAD

**Issue by Awekbing** [tiann/epic#2]
hook应用层的类可以  但是如果要hook  android.app.Activity 会卡死   
如果先调用原来的方法会卡死
如果后调用原来的方法提示找不到方法 DEBUG看了是方法名称对不上 
请问下  这是什么原因引起的呢

**Comment by rrrfff** [comment]
上代码看看

**Comment by Awekbing** [comment]
这是调用HOOK代码代码
`  try {
                    Method origin = Activity.class.getDeclaredMethod("onCreate", new Class[]{Bundle.class});
                    Method replace = HookCls1.class.getDeclaredMethod("onCreate", new Class[]{Bundle.class}); 
                    HookJavaMethod.hook(origin, replace); 
                } catch (Exception e) {
                    e.printStackTrace();
                }`
这是要替换的代码
`    public void onCreate(Bundle bundle) {
        String msg = "这是Hook之后的 onCreate";
        Log.d("Hook", msg  + this.getClass().getName()); 
        HookJavaMethod.callOrigin(this, bundle);
    }`

**Comment by tiann** [comment]
@Awekbing 使用的代码是啥样的？

**Comment by Awekbing** [comment]
HookJavaMethod就是你的那个代码没改动

**Comment by tiann** [comment]
@Awekbing 你改的哪个Activity的方法，又是怎么起来的

**Comment by tiann** [comment]
重新实现，关闭此issue。
