### ISSUE TITLE
针对不同classloader中的Method进行hook有bug

### ISSUE THREAD

**Issue by jarno520** [tiann/epic#20]
public static Unhook hookMethod(Member hookMethod, XC_MethodHook callback) {
		if (!(hookMethod instanceof Method) && !(hookMethod instanceof Constructor<?>)) {
			throw new IllegalArgumentException("only methods and constructors can be hooked");
		}

		boolean newMethod = false;
		CopyOnWriteSortedSet<XC_MethodHook> callbacks;
		synchronized (hookedMethodCallbacks) {
			callbacks = hookedMethodCallbacks.get(hookMethod);
			if (callbacks == null) {
				callbacks = new CopyOnWriteSortedSet<XC_MethodHook>();
				hookedMethodCallbacks.put(hookMethod, callbacks);
				newMethod = true;
			}
		}

这个地方的判断只是根据 hookedMethodCallbacks.get(hookMethod);进行了存储，当遇到某一个Method在不同的classloader都有时，就无法全部hook到了，第二个classloader会hook失败

**Comment by tiann** [comment]
感谢反馈，我看一下。

**Comment by tiann** [comment]
这个是符合预期的，Xposed也是这么做，要正确滴HOOK，必须要使用正确的ClassLoader去find这个Method。
如果不同ClassLoader加载的同一个Method都用一个东西去Hook，那么你的hook回调代码很可能是没法正常工作的。
