### ISSUE TITLE
CallMethod 疑问

### ISSUE THREAD

**Issue by Ericky1992** [tiann/epic#23]

**Comment by Ericky1992** [comment]
用的是最新的0.3.6，不知道是不是版本的问题

**Comment by Ericky1992** [comment]
好像直接把我的Int 转成了 Integer类啊？难道有int 类型的函数就不能call了啊？

**Comment by tiann** [comment]
不好意思，没明白你在讲什么

**Comment by Ericky1992** [comment]
你看Dexposed 里面的这个函数 Callmethod，	public static Object callMethod(Object obj, String methodName, Object... args) ，会把int 类型的参数转成 Integer类型的，导致最后call的时候找不到函数，从而出现java.lang.NoSuchMethodError: getItem(java.lang.Integer)#bestmatch

**Comment by tiann** [comment]
这个是Xposed的工具类，并非通用的。

**Comment by Ericky1992** [comment]
谢谢
