### ISSUE TITLE
是不是没法做到0侵入？要拿caller的引用必须得在目标类里加代码，有另外的java层hook思路吗？

### ISSUE THREAD

**Issue by tedzyc** [tiann/epic#3]
Hook.callOrigin()里用反射调用原方法必须得要原对象的引用（就是那个method invoke的receiver）。如果原对象是Activity我能想到的只能是在onCreate里把这个this记到我封装的xxActivityHooker里面。为此至少需在原Activity里加一行代码。可是hook的意义之一就是0侵入，让写业务Activity的人感知不到监控。所以想请维神指一下出路。

附：我用过dexposed写hook，确实没有对原有代码有任何的侵入。我这边的需求就在于监控方法调用的参数，原方法是肯定还会调用的。其实就是收集用户行为。比如从A页跳到B页，做一个上报之类的。dexposed的缺陷不说了，用Legend也是在一些机型上就报native层的崩溃。而且项目上一款机型不支持都是一票否决，所以感觉您的java层hook方案普适性很好。当然性能可能差些。用AspectJ挺麻烦的，所以还是希望出一个能覆盖较多安卓版本和机型的hook方案啊！

**Comment by tiann** [comment]
Dexposed是完整的AOP方案，这个项目只是个Hook框架；所以使用上肯定有差距。目前我有了纯Java的AOP思路了，不过还没有时间实现和填坑 :)

如果你仔细研究下ART的对象模型，会发现这个this不需要保存，这个this其实就是原来那个类的this。

**Comment by tedzyc** [comment]
嗯，期待大神的纯Java的AOP。
据我测试现有的这个框架已经很稳定。模拟器5.0-7.0上都能hook，小米5.1的机顶盒（那个用Legend不能hook的）上也能，但发现在华为荣耀6x真机上不能hook，估计是底层改太多了吧。just FYI。

**Comment by tiann** [comment]
@tedzyc 荣耀6x 不能Hook具体表现是什么样，卡死吗？还是有闪退

**Comment by tiann** [comment]
@tedzyc 已经重新实现了 :)
