### ISSUE TITLE
compile method failed

### ISSUE THREAD

**Issue by dcjniwota** [tiann/epic#31]
在项目工程中出现
 E epic.Epic: compile method failed...
但是在写的demo中没有出现此问题。
机型信息如下：
[cdma.version.baseband]: [SIXTH.CBP.MD.MP3.V95_P16, 2017/10/31 13:14]
[gsm.version.baseband]: [MOLY.LR11.W1603.MD.MP.V76.P30]
[gsm.version.baseband1]: [MOLY.LR11.W1603.MD.MP.V76.P30]
[gsm.version.ril-impl]: [android reference-ril 1.0]
[net.ims.ipsec.version]: [2.0]
[partition.version.verified]: [2]
[persist.mtk.wcn.patch.version]: [20170609182442a]
[ro.build.update_version]: [V1_2]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.emui]: [EmotionUI_5.1]
[ro.build.version.incremental]: [C00B155]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [7.0]
[ro.build.version.sdk]: [24]
[ro.build.version.security_patch]: [2017-11-05]
[ro.com.google.gmsversion]: [7.0_r12]
[ro.comp.cust_version]: [Cust-000000 5.0.0.1(0000)]
[ro.comp.product_version]: [Product-JMM 5.1.0.5(0000)]
[ro.comp.system_version]: [System 5.1.0.66(02LN)]
[ro.comp.version_version]: [Version-JMM-AL10-000001 5.1.0.3(00CF)]
[ro.config.sws_version]: [sws2]
[ro.cust.cdrom]: [/data/hw_init/version/region_comm/china/cdrom/autorun.iso]
[ro.mediatek.version.branch]: [alps-mp-n0.mp7]
[ro.mediatek.version.release]: [alps-mp-n0.mp7-V2.20_huawei6750.66.ot.n_P80]
[ro.mediatek.version.sdk]: [4]
[ro.opengles.version]: [196610]
[ro.product.hardwareversion]: [HL2JMMM]
[ro.versions.internal_sw_ver]: [Jimmy-AL10C00B155_2017121906]
[sys.aps.version]: [3.4.6-3.3.14]
请问一下出现compile method failed...有可能是什么原因呢。
04-06 16:58:22.177 16496 16605 W epic.DexposedBridge: Runtime.isArt(): true
04-06 16:58:22.177 16496 16605 W epic.DexposedBridge: hookMethod instanceof Method
04-06 16:58:22.178 16496 16605 I epic.Epic: Using: 64-bit ARM(Android M)
04-06 16:58:22.180 16496 16605 D richard : artOrigin is me.weishu.epic.art.method.ArtMethod@3fc6a7b
04-06 16:58:22.181 16496 16605 D epic.ArtMethod: not static, ignore.
04-06 16:58:22.182 16496 16605 D epic.EpicNative: Reading 8 bytes from: none in release mode.
04-06 16:58:22.182 16496 16605 D epic.EpicNative: none in release mode.
04-06 16:58:22.183 16496 16605 D epic.EpicNative: Reading 8 bytes from: none in release mode.
04-06 16:58:22.183 16496 16605 D epic.EpicNative: none in release mode.
04-06 16:58:22.183 16496 16605 I epic.Epic: this method is not compiled, compile it now. current entry: 0x70f44b21d0
04-06 16:58:22.184 16496 16605 E epic.Epic: compile method failed...
谢谢！

**Comment by tiann** [comment]
EMUI对JIT有修改，不主动编译即可。

**Comment by dcjniwota** [comment]
EMUI对JIT有修改，不主动编译即可
--可以说的具体一些么？目前是在epic库里面进行自动编译的哦，需要修改epic库拿掉这部分逻辑么？谢谢

**Comment by dcjniwota** [comment]
还有一个信息是：出现这种情况是在testCoverageEnabled true设置为true的情况下发生的。
使用JaCoCo用来收集代码覆盖率的
