### ISSUE TITLE
java.lang.VerifyError的问题

### ISSUE THREAD

**Issue by 122006** [tiann/epic#4]
你好，我用你的框架结合apt做了个动态注入框架功能。
但是在开始时替换方法产生了错误
java.lang.VerifyError: Verifier rejected class com.by122006library.Utils.ViewUtils due to bad method void com.by122006library.Utils.ViewUtils.smoothReplace(android.view.View, android.view.View, long) (declaration of 'com.by122006library.Utils.ViewUtils' appears in /data/app/com.by122006.modelprojectby122006-1/split_lib_slice_9_apk.apk)

AS自带热更新导致的原因么？

**Comment by 122006** [comment]
我试了签名，签名之后运行好像成功了。
应该是对多个分包的支持有待提升。

**Comment by tiann** [comment]
@122006 没太明白具体是什么情况 ，有更详细的信息或者说明吗？

**Comment by 122006** [comment]
方法替换要求两个方法都在一个dex中，如果采用分包（热更新、热修复、AS自带的Instant Run），都会可能导致两个方法不在同一个包里，就会出错。我之前直接调试的时候报VerifyError，后来关了AS的Instant Run就可以了

**Comment by goforit007** [comment]
@tiann  @122006 
分包（用于热更新和热修复) 导致的VerifyError有什么解决办法吗

**Comment by 122006** [comment]
@goforit007 我换用了aspectjx。如果只是替代非系统方法，建议使用aspectjx。

**Comment by goforit007** [comment]
@122006 感谢～ 如果必须使用这个epic前提下(项目需要) ,有什么好的办法么

**Comment by 122006** [comment]
@goforit007 如果是非系统api，可以用aspectjx来hook，如果是系统api，在程序application入口里用这个epic进行对系统的hook是没问题的

**Comment by goforit007** [comment]
@122006 明白了，感谢

**Comment by tiann** [comment]
已经重新实现，可以Hook系统方法；如果可以的话请帮忙测试一下，谢谢。
