### ISSUE TITLE
如何兼容art之前的模式？？？

### ISSUE THREAD

**Issue by johnx4** [tiann/epic#5]
如题

**Comment by tiann** [comment]
dalvik 请使用 [dexposed](https://github.com/alibaba/dexposed)

**Comment by johnx4** [comment]
有没有java部分的实现，想学习一下

**Comment by tiann** [comment]
没有。

其一，dexposed在dalvik下堪称完美，没必要重复造轮子。
其二，dalvik已经过时了，再去研究它意义不大。
