### ISSUE TITLE
hook是否影响其他方法的运行

### ISSUE THREAD

**Issue by iyy** [tiann/epic#8]
做了一个简单的IOMonitor来hook IOBridge的open,write,read方法,刚开始运行正常,点击一些功能后会报
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileDescriptor.sync()' on a null object reference
并没有hook sync方法
Rom:Android6.0

**Comment by tiann** [comment]
@iyy 是否有完整的堆栈和日志？有可能不是错误的Hook引起的，而是调用约定不对参数还原不正确。

**Comment by tiann** [comment]
能否提供下Hook的代码，以及发生异常时候的日志。

我这用6.0 的手机按照你说的场景，没有复现。

**Comment by iyy** [comment]
接入我们app内部的不太方便提供堆栈,不过看堆栈是SharedPerence的commit的时候执行了一个文件sync,你写一个sp的读写和commit,apply试试,我是荣耀6

**Comment by tiann** [comment]
可否把你所有的Hook代码，以及去除敏感堆栈的堆栈发出来看下？实在复现不了，靠猜解决不了问题。

**Comment by iyy** [comment]
![image](https://user-images.githubusercontent.com/1791358/33300786-200ac3cc-d42d-11e7-8e82-b2c6c1a860cc.png)
stack:
![image](https://user-images.githubusercontent.com/1791358/33300801-30410a58-d42d-11e7-9603-99af9d4e574b.png)

**Comment by tiann** [comment]
@iyy 已经修复此问题，原因是Hook调用原函数对异常处理考虑步骤引起的；感谢反馈。

可以使用  0.1.4 版本测试一下，应该没问题了。
